### ISSUE TITLE
Invariant Violation: Attempted to update component `ProfileOrganizationsView` that has already been unmounted (or fail...

### ISSUE THREAD

**Issue by ovr** [ovr/ghubber#17]
https://sentry.io/ghubber/android/issues/294449492/

```
Invariant Violation: Attempted to update component `ProfileOrganizationsView` that has already been unmounted (or failed to mount).
    at updateComponent(index.android.bundle:25042)
    at _performComponentUpdate(index.android.bundle:25123)
    at _updateRenderedComponent(index.android.bundle:25157)
    at _updateRenderedComponentWithNextElement(index.android.bundle:25170)
    at receiveComponent(index.android.bundle:23847)
...
(45 additional frame(s) were not displayed)
```

**Comment by ovr** [comment]
@lex111 is it you?)

**Comment by lex111** [comment]
@ovr oops, it's me. Sorry about that.

It is called, took up the RN :(
How can I disable logging?

**Comment by lex111** [comment]
I typed the fake url in Sentry.config, now there should not be such.. I wanted to do something, a little UI-improvement, but the attempt failed :disappointed:

**Comment by lex111** [comment]
Returning to the commin topic, I have these thoughts:

1. Create a config file with the object, for example `config.js`, where there will be a key, like SENTRY_URL, this file will be ignored by Git, or as an alternative, store this information in an `.env` file (you need to decide what is best).
2. Accordingly, if SENTRY_URL is not empty, initialize Sentry, but because in app, Sentry methods are used, then you need to check that the Sentry is initialized (available), so you might consider creating a wrapper over Sentry in the `util` folder, e.g., something like Logger.js? And can Sentry not be connect in the DEV environment?

**Comment by ovr** [comment]
@lex111 I will think a little bit about this issue, thank you

**Comment by lex111** [comment]
@ovr ...but write decision on the issue, I'll send PR! :smirk:
